<?php

namespace Gecche\Cupparis\DatafileJson\Breeze\Concerns;

use Closure;

use Gecche\Breeze\Breeze;
use Gecche\Cupparis\Datafile\Breeze\Concerns\HasDatafileValidation;
use Gecche\Cupparis\Datafile\Models\DatafileError;
use Gecche\DBHelper\Facades\DBHelper;
use Illuminate\Support\Arr;

use Exception;
use Illuminate\Support\Facades\Log;

trait BreezeDatafileJsonTrait {



    public function getDatafileIdField()
    {
        return $this->datafile_id_field;
    }

    /**
     * @param string $datafile_id_field
     */
    public function setDatafileIdField($datafile_id_field)
    {
        $this->datafile_id_field = $datafile_id_field;
    }

    /**
     * @return string
     */
    public function getRowIndexField()
    {
        return $this->row_index_field;
    }

    /**
     * @param string $row_index_field
     */
    public function setRowIndexField($row_index_field)
    {
        $this->row_index_field = $row_index_field;
    }

    /**
     * @return string
     */
    public function getDatafileSheetField(): string
    {
        return $this->datafile_sheet_field;
    }

    /**
     * @param string $datafile_sheet_field
     */
    public function setDatafileSheetField(string $datafile_sheet_field): void
    {
        $this->datafile_sheet_field = $datafile_sheet_field;
    }

    /**
     * @return string
     */
    public function getDatafileIdValue()
    {
        return $this->{$this->datafile_id_field};
    }

    /**
     * @return string
     */
    public function setDatafileIdValue($datafileIdValue)
    {
        $this->{$this->datafile_id_field} = $datafileIdValue;
    }

    /**
     * @return string
     */
    public function getRowIndexValue()
    {
        return $this->{$this->row_index_field};
    }

    /**
     * @return string
     */
    public function setRowIndexValue($rowIndexValue)
    {
        $this->{$this->row_index_field} = $rowIndexValue;
    }

    /**
     * @return string
     */
    public function getDatafileSheetValue()
    {
        return $this->{$this->datafile_sheet_field};
    }

    /**
     * @return string
     */
    public function setDatafileSheetValue($datafileSheetValue)
    {

        //Log::info("SETDATAFILESHEETVALUE:: ". $this->datafile_sheet_field . ' --- ' . $datafileSheetValue);
        $this->{$this->datafile_sheet_field} = $datafileSheetValue;
    }





    /*
     * VALIDAZIONE AL SALVATAGGIO DA CAMBIARE
     */

    public function validateDatafile(array $rules = array(), array $customMessages = array(),$datafile_id = null) {
        $rules = $this->buildUniqueDatafileRules($rules,$datafile_id);
        $rules = $this->buildExistsDatafileRules($rules,$datafile_id);
        return $this->validate($rules,$customMessages);
    }

    public function saveDatafile(
        $datafile_id = null,
        array $rules = array(),
        array $customMessages = array(),
        array $options = array(),
        \Closure $beforeSave = null,
        \Closure $afterSave = null
    ) {

        $rules = $this->buildUniqueDatafileRules($rules,$datafile_id);
        $rules = $this->buildExistsDatafileRules($rules,$datafile_id);
        return $this->forceSave($rules, $customMessages, $options, $beforeSave,
            $afterSave); // TODO: Change the autogenerated stub
    }

    public function fillDatafile(array $attributes)
    {
        $rowDataAttributes = $this->buildRowDataValuesAndErrors($attributes);
        return parent::fill(['row_data' => $rowDataAttributes]); // TODO: Change the autogenerated stub
    }

    public function buildRowDataValuesAndErrors(array $attributes, array $errors = []) {
        if (count($errors) == 0) {
            $errors = array_fill_keys(array_keys($attributes),[]);
        }
        $rowData = [
            'values' => $attributes,
            'errors' => $errors,
        ];
        return $rowData;
    }

    public function getRowDataValues() {

        $rowData = $this->row_data;
        return Arr::get($rowData,'values',[]);

    }

    public function setRowDataErrors(array $errors = []) {
        $rowData = $this->row_data;

        if (!$rowData) {
            $rowData = $this->buildRowDataValuesAndErrors([],$errors);
        } else {
            $rowData['errors'] = $errors;
        }

        $this->row_data = $rowData;
    }

    public function setHasErrors(bool $hasErrors) {

        $this->has_errors = $hasErrors;

    }

    public function getHasErrors() {

        return (bool) $this->has_errors;

    }


}

// End Datafile Core Model
