<?php

namespace Gecche\Cupparis\DatafileJson\Models;

use Gecche\Breeze\Breeze;
use Gecche\Cupparis\App\Models\CupparisEntity;
use Gecche\Cupparis\DatafileJson\Breeze\Concerns\HasDatafileJsonValidation;
use Gecche\Cupparis\DatafileJson\Breeze\Contracts\HasDatafileJsonValidationInterface;
use Gecche\Cupparis\DatafileJson\Models\Relations\DatafileJsonRowRelations;
use Gecche\DBHelper\Facades\DBHelper;

class DatafileJsonRow extends Breeze implements HasDatafileJsonValidationInterface {

    use DatafileJsonRowRelations;
    use HasDatafileJsonValidation;

    protected $table = 'datafiles_json_rows';

    protected $guarded = ['id'];


    public $timestamps = true;
    public $ownerships = true;

    public $casts = [
        'row_data' => 'array',
    ];

    // campi predefiniti, necessari per il funzionamento del modello
    public $datafile_id_field = 'datafile_id';
    public $row_index_field = 'row';
    public $datafile_sheet_field = 'datafile_sheet';


    public $headers;

    public static $relationsData = array(
        //'address' => array(self::HAS_ONE, 'Address'),
        //'orders'  => array(self::HAS_MANY, 'Order'),

        'datafile' => [self::MORPH_ONE,
            'related' => DatafileJson::class,
            'name' => 'datafile',
            'id' => 'datafile_id',
            'type' => 'datafile_type'
        ],
    );

    /**
     * @return string
     */
    public function getDatafileIdField()
    {
        return $this->datafile_id_field;
    }

    /**
     * @param string $datafile_id_field
     */
    public function setDatafileIdField($datafile_id_field)
    {
        $this->datafile_id_field = $datafile_id_field;
    }

    /**
     * @return string
     */
    public function getRowIndexField()
    {
        return $this->row_index_field;
    }

    /**
     * @param string $row_index_field
     */
    public function setRowIndexField($row_index_field)
    {
        $this->row_index_field = $row_index_field;
    }

    /**
     * @return string
     */
    public function getDatafileSheetField(): string
    {
        return $this->datafile_sheet_field;
    }

    /**
     * @param string $datafile_sheet_field
     */
    public function setDatafileSheetField(string $datafile_sheet_field): void
    {
        $this->datafile_sheet_field = $datafile_sheet_field;
    }

    /**
     * @return string
     */
    public function getDatafileIdValue()
    {
        return $this->{$this->datafile_id_field};
    }

    /**
     * @return string
     */
    public function setDatafileIdValue($datafileIdValue)
    {
        $this->{$this->datafile_id_field} = $datafileIdValue;
    }

    /**
     * @return string
     */
    public function getRowIndexValue()
    {
        return $this->{$this->row_index_field};
    }

    /**
     * @return string
     */
    public function setRowIndexValue($rowIndexValue)
    {
        $this->{$this->row_index_field} = $rowIndexValue;
    }

    /**
     * @return string
     */
    public function getDatafileSheetValue()
    {
        return $this->{$this->datafile_sheet_field};
    }

    /**
     * @return string
     */
    public function setDatafileSheetValue($datafileSheetValue)
    {

        //Log::info("SETDATAFILESHEETVALUE:: ". $this->datafile_sheet_field . ' --- ' . $datafileSheetValue);
        $this->{$this->datafile_sheet_field} = $datafileSheetValue;
    }





    /*
     * VALIDAZIONE AL SALVATAGGIO DA CAMBIARE
     */

    public function validateDatafile(array $rules = array(), array $customMessages = array(),$datafile_id = null) {
        $rules = $this->buildUniqueDatafileRules($rules,$datafile_id);
        $rules = $this->buildExistsDatafileRules($rules,$datafile_id);
        return $this->validate($rules,$customMessages);
    }

    public function saveDatafile(
        $datafile_id = null,
        array $rules = array(),
        array $customMessages = array(),
        array $options = array(),
        \Closure $beforeSave = null,
        \Closure $afterSave = null
    ) {

        $rules = $this->buildUniqueDatafileRules($rules,$datafile_id);
        $rules = $this->buildExistsDatafileRules($rules,$datafile_id);
        return $this->forceSave($rules, $customMessages, $options, $beforeSave,
            $afterSave); // TODO: Change the autogenerated stub
    }

    public function fill(array $attributes)
    {
        $rowDataAttributes = $this->buildRowDataValuesAndErrors($attributes);
        return parent::fill($rowDataAttributes); // TODO: Change the autogenerated stub
    }

    public function buildRowDataValuesAndErrors(array $attributes, array $errors = []) {
        if (count($errors) == 0) {
            $errors = array_fill_keys(array_keys($attributes),[]);
        }
        $rowData = [
            'values' => $attributes,
            'errors' => $errors,
        ];
        return ['row_data' => $rowData];
    }

    public function setRowDataErrors(array $errors = []) {
        $rowData = $this->row_data;

        if (!$rowData) {
            $rowData = $this->buildRowDataValuesAndErrors([],$errors);
        } else {
            $rowData['errors'] = $errors;
        }

        $this->row_data = ['row_data' => $rowData];
    }


}
